-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.ai_chat_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['user'::text, 'assistant'::text, 'system'::text])),
  content text NOT NULL,
  tokens_used integer,
  model text,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT ai_chat_messages_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.ai_chat_sessions(id),
  CONSTRAINT ai_chat_messages_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.ai_chat_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  user_id uuid NOT NULL,
  title text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_chat_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT ai_chat_sessions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT ai_chat_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.ai_insights (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  insight_type text NOT NULL CHECK (insight_type = ANY (ARRAY['turnover_risk'::text, 'attendance_anomaly'::text, 'leave_pattern'::text, 'payroll_anomaly'::text, 'performance_trend'::text, 'recruitment_funnel'::text, 'overtime_alert'::text, 'compliance_risk'::text])),
  title text NOT NULL,
  summary text NOT NULL,
  severity text NOT NULL DEFAULT 'info'::text CHECK (severity = ANY (ARRAY['info'::text, 'warning'::text, 'critical'::text])),
  reference_type text,
  reference_id uuid,
  employee_id uuid,
  data_payload jsonb,
  is_dismissed boolean NOT NULL DEFAULT false,
  dismissed_by uuid,
  dismissed_at timestamp with time zone,
  expires_at timestamp with time zone,
  generated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_insights_pkey PRIMARY KEY (id),
  CONSTRAINT ai_insights_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT ai_insights_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT ai_insights_dismissed_by_fkey FOREIGN KEY (dismissed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.api_keys (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  key_hash text NOT NULL,
  key_prefix text NOT NULL,
  scopes ARRAY NOT NULL DEFAULT '{}'::text[],
  last_used_at timestamp with time zone,
  expires_at timestamp with time zone,
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid NOT NULL,
  revoked_by uuid,
  revoked_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT api_keys_pkey PRIMARY KEY (id),
  CONSTRAINT api_keys_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT api_keys_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT api_keys_revoked_by_fkey FOREIGN KEY (revoked_by) REFERENCES auth.users(id)
);
CREATE TABLE public.applicant_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  applicant_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  note text NOT NULL,
  is_private boolean NOT NULL DEFAULT false,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT applicant_notes_pkey PRIMARY KEY (id),
  CONSTRAINT applicant_notes_applicant_id_fkey FOREIGN KEY (applicant_id) REFERENCES public.applicants(id),
  CONSTRAINT applicant_notes_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT applicant_notes_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.applicants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  job_posting_id uuid NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text NOT NULL,
  phone text,
  current_employer text,
  current_position text,
  years_experience integer,
  expected_salary numeric,
  resume_url text,
  cover_letter text,
  source text NOT NULL DEFAULT 'direct'::text CHECK (source = ANY (ARRAY['direct'::text, 'linkedin'::text, 'indeed'::text, 'jobstreet'::text, 'kalibrr'::text, 'referral'::text, 'walk_in'::text, 'other'::text])),
  referrer_employee_id uuid,
  status text NOT NULL DEFAULT 'new'::text CHECK (status = ANY (ARRAY['new'::text, 'screening'::text, 'interview'::text, 'assessment'::text, 'offer'::text, 'hired'::text, 'rejected'::text, 'withdrawn'::text])),
  rejected_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT applicants_pkey PRIMARY KEY (id),
  CONSTRAINT applicants_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT applicants_job_posting_id_fkey FOREIGN KEY (job_posting_id) REFERENCES public.job_postings(id),
  CONSTRAINT applicants_referrer_employee_id_fkey FOREIGN KEY (referrer_employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.attendance_corrections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  attendance_log_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  correction_type text NOT NULL CHECK (correction_type = ANY (ARRAY['time_in'::text, 'time_out'::text, 'break_in'::text, 'break_out'::text, 'status'::text, 'hours'::text])),
  original_value text,
  corrected_value text NOT NULL,
  reason text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  approved_by uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT attendance_corrections_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_corrections_attendance_log_id_fkey FOREIGN KEY (attendance_log_id) REFERENCES public.attendance_logs(id),
  CONSTRAINT attendance_corrections_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT attendance_corrections_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT attendance_corrections_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.attendance_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  schedule_id uuid,
  log_date date NOT NULL,
  time_in timestamp with time zone,
  time_out timestamp with time zone,
  break_in timestamp with time zone,
  break_out timestamp with time zone,
  hours_worked numeric,
  overtime_hours numeric NOT NULL DEFAULT 0,
  late_minutes integer NOT NULL DEFAULT 0,
  undertime_minutes integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'present'::text CHECK (status = ANY (ARRAY['present'::text, 'absent'::text, 'late'::text, 'half_day'::text, 'on_leave'::text, 'holiday'::text, 'rest_day'::text, 'work_from_home'::text])),
  source text NOT NULL DEFAULT 'manual'::text CHECK (source = ANY (ARRAY['biometric'::text, 'mobile'::text, 'web'::text, 'manual'::text])),
  location_lat numeric,
  location_lng numeric,
  selfie_url text,
  notes text,
  is_corrected boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT attendance_logs_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_logs_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT attendance_logs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT attendance_logs_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES public.schedules(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  user_id uuid,
  action text NOT NULL CHECK (action = ANY (ARRAY['create'::text, 'update'::text, 'delete'::text, 'view'::text, 'export'::text, 'login'::text, 'logout'::text, 'login_failed'::text, 'password_changed'::text, 'role_assigned'::text, 'role_removed'::text, 'payroll_run'::text, 'payslip_released'::text, 'document_signed'::text, 'document_downloaded'::text, 'bulk_import'::text, 'bulk_export'::text, 'settings_changed'::text, 'api_key_created'::text, 'api_key_revoked'::text])),
  resource_type text NOT NULL,
  resource_id uuid,
  old_values jsonb,
  new_values jsonb,
  changed_fields ARRAY,
  ip_address text,
  user_agent text,
  session_id text,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.benefits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['hmo'::text, 'life_insurance'::text, 'accident_insurance'::text, 'dental'::text, 'optical'::text, 'allowance'::text, 'other'::text])),
  description text,
  provider text,
  coverage_amount numeric,
  premium_ee numeric NOT NULL DEFAULT 0,
  premium_er numeric NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT benefits_pkey PRIMARY KEY (id),
  CONSTRAINT benefits_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.bir_alphalist_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  tin text,
  last_name text NOT NULL,
  first_name text NOT NULL,
  middle_name text,
  classification text NOT NULL DEFAULT 'MWE'::text CHECK (classification = ANY (ARRAY['MWE'::text, 'NMW'::text, 'P'::text, 'HF'::text, 'S'::text])),
  gross_compensation numeric NOT NULL DEFAULT 0,
  non_taxable_comp numeric NOT NULL DEFAULT 0,
  taxable_comp numeric NOT NULL DEFAULT 0,
  tax_withheld numeric NOT NULL DEFAULT 0,
  thirteenth_month numeric NOT NULL DEFAULT 0,
  other_benefits numeric NOT NULL DEFAULT 0,
  sss_contribution numeric NOT NULL DEFAULT 0,
  philhealth_contrib numeric NOT NULL DEFAULT 0,
  pagibig_contrib numeric NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT bir_alphalist_records_pkey PRIMARY KEY (id),
  CONSTRAINT bir_alphalist_records_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.compliance_reports(id),
  CONSTRAINT bir_alphalist_records_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT bir_alphalist_records_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.branches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  code text NOT NULL,
  address jsonb,
  is_head_office boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT branches_pkey PRIMARY KEY (id),
  CONSTRAINT branches_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.clearance_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  checklist_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  department text NOT NULL DEFAULT 'hr'::text CHECK (department = ANY (ARRAY['hr'::text, 'it'::text, 'finance'::text, 'admin'::text, 'operations'::text, 'general'::text])),
  is_required boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT clearance_items_pkey PRIMARY KEY (id),
  CONSTRAINT clearance_items_checklist_id_fkey FOREIGN KEY (checklist_id) REFERENCES public.offboarding_checklists(id),
  CONSTRAINT clearance_items_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.clearance_progress (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  offboarding_id uuid NOT NULL,
  clearance_item_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'cleared'::text, 'held'::text])),
  cleared_by uuid,
  cleared_at timestamp with time zone,
  remarks text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT clearance_progress_pkey PRIMARY KEY (id),
  CONSTRAINT clearance_progress_offboarding_id_fkey FOREIGN KEY (offboarding_id) REFERENCES public.offboarding_records(id),
  CONSTRAINT clearance_progress_clearance_item_id_fkey FOREIGN KEY (clearance_item_id) REFERENCES public.clearance_items(id),
  CONSTRAINT clearance_progress_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT clearance_progress_cleared_by_fkey FOREIGN KEY (cleared_by) REFERENCES auth.users(id)
);
CREATE TABLE public.compliance_deadlines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  agency text NOT NULL CHECK (agency = ANY (ARRAY['bir'::text, 'sss'::text, 'philhealth'::text, 'pagibig'::text, 'dole'::text])),
  report_type text NOT NULL,
  period_year integer NOT NULL,
  period_month integer CHECK (period_month >= 1 AND period_month <= 12),
  period_quarter integer CHECK (period_quarter >= 1 AND period_quarter <= 4),
  due_date date NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'filed'::text, 'overdue'::text, 'waived'::text])),
  filed_at timestamp with time zone,
  report_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT compliance_deadlines_pkey PRIMARY KEY (id),
  CONSTRAINT compliance_deadlines_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT compliance_deadlines_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.compliance_reports(id)
);
CREATE TABLE public.compliance_remittances (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  agency text NOT NULL CHECK (agency = ANY (ARRAY['bir'::text, 'sss'::text, 'philhealth'::text, 'pagibig'::text])),
  amount numeric NOT NULL,
  payment_date date,
  reference_no text,
  channel text CHECK (channel = ANY (ARRAY['online'::text, 'bank'::text, 'cash'::text, 'gcash'::text, 'paymaya'::text])),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'paid'::text, 'failed'::text])),
  receipt_url text,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT compliance_remittances_pkey PRIMARY KEY (id),
  CONSTRAINT compliance_remittances_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.compliance_reports(id),
  CONSTRAINT compliance_remittances_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT compliance_remittances_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.compliance_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  report_type text NOT NULL CHECK (report_type = ANY (ARRAY['bir_alphalist'::text, 'bir_2316'::text, 'bir_1601c'::text, 'bir_1604cf'::text, 'sss_r3'::text, 'sss_r1a'::text, 'sss_salary_loan'::text, 'philhealth_rf1'::text, 'pagibig_mpl'::text, 'pagibig_monthly'::text, 'dole_employment_report'::text])),
  period_type text NOT NULL DEFAULT 'monthly'::text CHECK (period_type = ANY (ARRAY['monthly'::text, 'quarterly'::text, 'annual'::text])),
  period_year integer NOT NULL,
  period_month integer CHECK (period_month >= 1 AND period_month <= 12),
  period_quarter integer CHECK (period_quarter >= 1 AND period_quarter <= 4),
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'generated'::text, 'submitted'::text, 'accepted'::text, 'rejected'::text])),
  generated_at timestamp with time zone,
  submitted_at timestamp with time zone,
  file_path text,
  submission_ref text,
  notes text,
  generated_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT compliance_reports_pkey PRIMARY KEY (id),
  CONSTRAINT compliance_reports_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT compliance_reports_generated_by_fkey FOREIGN KEY (generated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.contact_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  email text NOT NULL,
  subject text NOT NULL,
  message text NOT NULL,
  status text NOT NULL DEFAULT 'unread'::text CHECK (status = ANY (ARRAY['unread'::text, 'read'::text, 'replied'::text, 'archived'::text])),
  ip_hash text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT contact_messages_pkey PRIMARY KEY (id)
);
CREATE TABLE public.dashboard_snapshots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  snapshot_date date NOT NULL,
  metric_type text NOT NULL CHECK (metric_type = ANY (ARRAY['headcount'::text, 'turnover'::text, 'attendance_rate'::text, 'leave_utilization'::text, 'overtime_hours'::text, 'payroll_cost'::text, 'open_positions'::text, 'avg_time_to_hire'::text, 'pending_approvals'::text])),
  value numeric NOT NULL,
  breakdown jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT dashboard_snapshots_pkey PRIMARY KEY (id),
  CONSTRAINT dashboard_snapshots_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.data_retention_policies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  resource_type text NOT NULL,
  retention_days integer NOT NULL,
  auto_delete boolean NOT NULL DEFAULT false,
  last_run_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT data_retention_policies_pkey PRIMARY KEY (id),
  CONSTRAINT data_retention_policies_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.demo_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  email text NOT NULL,
  phone text,
  company text NOT NULL,
  company_size text,
  industry text,
  preferred_date date,
  status text NOT NULL DEFAULT 'new'::text CHECK (status = ANY (ARRAY['new'::text, 'contacted'::text, 'scheduled'::text, 'completed'::text, 'cancelled'::text])),
  notes text,
  ip_hash text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT demo_requests_pkey PRIMARY KEY (id)
);
CREATE TABLE public.departments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  code text NOT NULL,
  description text,
  head_id uuid,
  parent_id uuid,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT departments_pkey PRIMARY KEY (id),
  CONSTRAINT departments_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT departments_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.departments(id),
  CONSTRAINT fk_department_head FOREIGN KEY (head_id) REFERENCES public.employees(id)
);
CREATE TABLE public.document_access_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  document_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  accessed_by uuid NOT NULL,
  action text NOT NULL CHECK (action = ANY (ARRAY['view'::text, 'download'::text, 'print'::text, 'share'::text])),
  ip_address text,
  accessed_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT document_access_logs_pkey PRIMARY KEY (id),
  CONSTRAINT document_access_logs_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(id),
  CONSTRAINT document_access_logs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT document_access_logs_accessed_by_fkey FOREIGN KEY (accessed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.document_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  code text NOT NULL,
  description text,
  requires_signature boolean NOT NULL DEFAULT false,
  retention_years integer,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT document_categories_pkey PRIMARY KEY (id),
  CONSTRAINT document_categories_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.document_shares (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  document_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  shared_with uuid NOT NULL,
  permission text NOT NULL DEFAULT 'view'::text CHECK (permission = ANY (ARRAY['view'::text, 'download'::text, 'edit'::text])),
  expires_at timestamp with time zone,
  shared_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT document_shares_pkey PRIMARY KEY (id),
  CONSTRAINT document_shares_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(id),
  CONSTRAINT document_shares_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT document_shares_shared_with_fkey FOREIGN KEY (shared_with) REFERENCES auth.users(id),
  CONSTRAINT document_shares_shared_by_fkey FOREIGN KEY (shared_by) REFERENCES auth.users(id)
);
CREATE TABLE public.document_versions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  document_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  version integer NOT NULL,
  file_name text NOT NULL,
  file_path text NOT NULL,
  file_size integer,
  change_summary text,
  uploaded_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT document_versions_pkey PRIMARY KEY (id),
  CONSTRAINT document_versions_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(id),
  CONSTRAINT document_versions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT document_versions_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id)
);
CREATE TABLE public.documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  employee_id uuid,
  category_id uuid,
  title text NOT NULL,
  description text,
  file_name text NOT NULL,
  file_path text NOT NULL,
  file_size integer,
  mime_type text,
  version integer NOT NULL DEFAULT 1,
  is_template boolean NOT NULL DEFAULT false,
  is_confidential boolean NOT NULL DEFAULT false,
  expires_at date,
  tags ARRAY,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'archived'::text, 'expired'::text])),
  uploaded_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT documents_pkey PRIMARY KEY (id),
  CONSTRAINT documents_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT documents_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT documents_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.document_categories(id),
  CONSTRAINT documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id)
);
CREATE TABLE public.e_signatures (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  document_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  signer_id uuid NOT NULL,
  employee_id uuid,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'signed'::text, 'declined'::text, 'expired'::text])),
  signed_at timestamp with time zone,
  declined_at timestamp with time zone,
  decline_reason text,
  signature_data text,
  ip_address text,
  signature_order integer NOT NULL DEFAULT 1,
  due_date date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT e_signatures_pkey PRIMARY KEY (id),
  CONSTRAINT e_signatures_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(id),
  CONSTRAINT e_signatures_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT e_signatures_signer_id_fkey FOREIGN KEY (signer_id) REFERENCES auth.users(id),
  CONSTRAINT e_signatures_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.email_queue (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  recipient_email text NOT NULL,
  recipient_name text,
  subject text NOT NULL,
  html_body text NOT NULL,
  text_body text,
  reply_to text,
  template_id uuid,
  reference_type text,
  reference_id uuid,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'sending'::text, 'sent'::text, 'failed'::text, 'cancelled'::text])),
  attempts integer NOT NULL DEFAULT 0,
  last_attempted_at timestamp with time zone,
  sent_at timestamp with time zone,
  error_message text,
  provider_message_id text,
  scheduled_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT email_queue_pkey PRIMARY KEY (id),
  CONSTRAINT email_queue_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT email_queue_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.notification_templates(id)
);
CREATE TABLE public.employee_bank_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  bank_name text NOT NULL,
  account_name text NOT NULL,
  account_number text NOT NULL,
  account_type text NOT NULL DEFAULT 'savings'::text CHECK (account_type = ANY (ARRAY['savings'::text, 'checking'::text, 'payroll'::text])),
  is_primary boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employee_bank_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT employee_bank_accounts_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_bank_accounts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.employee_beneficiaries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  name text NOT NULL,
  relationship text NOT NULL,
  share_percent numeric CHECK (share_percent >= 0::numeric AND share_percent <= 100::numeric),
  date_of_birth date,
  contact_number text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employee_beneficiaries_pkey PRIMARY KEY (id),
  CONSTRAINT employee_beneficiaries_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_beneficiaries_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.employee_benefits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  benefit_id uuid NOT NULL,
  hmo_plan_id uuid,
  effective_date date NOT NULL,
  end_date date,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'pending'::text, 'cancelled'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employee_benefits_pkey PRIMARY KEY (id),
  CONSTRAINT employee_benefits_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_benefits_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT employee_benefits_benefit_id_fkey FOREIGN KEY (benefit_id) REFERENCES public.benefits(id),
  CONSTRAINT employee_benefits_hmo_plan_id_fkey FOREIGN KEY (hmo_plan_id) REFERENCES public.hmo_plans(id)
);
CREATE TABLE public.employee_compensation (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  rate_type text NOT NULL DEFAULT 'monthly'::text CHECK (rate_type = ANY (ARRAY['monthly'::text, 'daily'::text, 'hourly'::text])),
  basic_salary numeric NOT NULL DEFAULT 0,
  hourly_rate numeric,
  daily_rate numeric,
  currency text NOT NULL DEFAULT 'PHP'::text,
  effective_date date NOT NULL,
  end_date date,
  is_current boolean NOT NULL DEFAULT true,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employee_compensation_pkey PRIMARY KEY (id),
  CONSTRAINT employee_compensation_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_compensation_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.employee_dependents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  relationship text NOT NULL CHECK (relationship = ANY (ARRAY['spouse'::text, 'child'::text, 'parent'::text, 'sibling'::text, 'other'::text])),
  date_of_birth date,
  is_dependent_for_tax boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employee_dependents_pkey PRIMARY KEY (id),
  CONSTRAINT employee_dependents_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_dependents_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.employee_emergency_contacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  name text NOT NULL,
  relationship text NOT NULL,
  mobile_number text NOT NULL,
  phone_number text,
  address text,
  is_primary boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employee_emergency_contacts_pkey PRIMARY KEY (id),
  CONSTRAINT employee_emergency_contacts_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_emergency_contacts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.employee_employment (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  branch_id uuid,
  department_id uuid,
  position_id uuid,
  employment_type_id uuid,
  direct_manager_id uuid,
  date_hired date NOT NULL,
  date_regularized date,
  date_separated date,
  separation_reason text,
  work_arrangement text NOT NULL DEFAULT 'on_site'::text CHECK (work_arrangement = ANY (ARRAY['on_site'::text, 'remote'::text, 'hybrid'::text])),
  work_schedule text,
  is_current boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employee_employment_pkey PRIMARY KEY (id),
  CONSTRAINT employee_employment_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_employment_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT employee_employment_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT employee_employment_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT employee_employment_position_id_fkey FOREIGN KEY (position_id) REFERENCES public.positions(id),
  CONSTRAINT employee_employment_employment_type_id_fkey FOREIGN KEY (employment_type_id) REFERENCES public.employment_types(id),
  CONSTRAINT employee_employment_direct_manager_id_fkey FOREIGN KEY (direct_manager_id) REFERENCES public.employees(id)
);
CREATE TABLE public.employee_goals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  cycle_id uuid,
  title text NOT NULL,
  description text,
  target_date date,
  progress integer NOT NULL DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'completed'::text, 'cancelled'::text])),
  priority text NOT NULL DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text])),
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employee_goals_pkey PRIMARY KEY (id),
  CONSTRAINT employee_goals_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_goals_cycle_id_fkey FOREIGN KEY (cycle_id) REFERENCES public.review_cycles(id),
  CONSTRAINT employee_goals_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT employee_goals_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.employee_government_ids (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL UNIQUE,
  organization_id uuid NOT NULL,
  sss_number text,
  tin_number text,
  pagibig_number text,
  philhealth_number text,
  umid_number text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employee_government_ids_pkey PRIMARY KEY (id),
  CONSTRAINT employee_government_ids_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT employee_government_ids_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.employee_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cycle_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  reviewer_id uuid NOT NULL,
  template_id uuid,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'self_review'::text, 'manager_review'::text, 'calibration'::text, 'completed'::text, 'cancelled'::text])),
  self_score numeric,
  manager_score numeric,
  final_score numeric,
  rating text CHECK (rating = ANY (ARRAY['exceptional'::text, 'exceeds_expectations'::text, 'meets_expectations'::text, 'needs_improvement'::text, 'unsatisfactory'::text])),
  self_submitted_at timestamp with time zone,
  manager_submitted_at timestamp with time zone,
  completed_at timestamp with time zone,
  remarks text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employee_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT employee_reviews_cycle_id_fkey FOREIGN KEY (cycle_id) REFERENCES public.review_cycles(id),
  CONSTRAINT employee_reviews_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT employee_reviews_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES auth.users(id),
  CONSTRAINT employee_reviews_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.review_templates(id)
);
CREATE TABLE public.employee_schedules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  schedule_id uuid NOT NULL,
  effective_date date NOT NULL,
  end_date date,
  is_current boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employee_schedules_pkey PRIMARY KEY (id),
  CONSTRAINT employee_schedules_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_schedules_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT employee_schedules_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES public.schedules(id)
);
CREATE TABLE public.employees (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  user_id uuid,
  employee_no text NOT NULL,
  first_name text NOT NULL,
  middle_name text,
  last_name text NOT NULL,
  suffix text,
  preferred_name text,
  gender text CHECK (gender = ANY (ARRAY['male'::text, 'female'::text, 'non_binary'::text, 'prefer_not_to_say'::text])),
  civil_status text CHECK (civil_status = ANY (ARRAY['single'::text, 'married'::text, 'widowed'::text, 'separated'::text, 'divorced'::text])),
  date_of_birth date,
  place_of_birth text,
  nationality text NOT NULL DEFAULT 'Filipino'::text,
  religion text,
  blood_type text CHECK (blood_type = ANY (ARRAY['A+'::text, 'A-'::text, 'B+'::text, 'B-'::text, 'AB+'::text, 'AB-'::text, 'O+'::text, 'O-'::text, 'unknown'::text])),
  personal_email text,
  work_email text,
  mobile_number text,
  phone_number text,
  address_line1 text,
  address_line2 text,
  city text,
  province text,
  zip_code text,
  country text NOT NULL DEFAULT 'Philippines'::text,
  avatar_url text,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'on_leave'::text, 'terminated'::text, 'resigned'::text, 'retired'::text])),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employees_pkey PRIMARY KEY (id),
  CONSTRAINT employees_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT employees_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.employment_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  code text NOT NULL,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  CONSTRAINT employment_types_pkey PRIMARY KEY (id),
  CONSTRAINT employment_types_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.exit_interviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  offboarding_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  scheduled_at timestamp with time zone,
  conducted_at timestamp with time zone,
  conducted_by uuid,
  primary_reason text,
  would_recommend boolean,
  satisfaction_score integer CHECK (satisfaction_score >= 1 AND satisfaction_score <= 10),
  feedback text,
  is_confidential boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT exit_interviews_pkey PRIMARY KEY (id),
  CONSTRAINT exit_interviews_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT exit_interviews_offboarding_id_fkey FOREIGN KEY (offboarding_id) REFERENCES public.offboarding_records(id),
  CONSTRAINT exit_interviews_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT exit_interviews_conducted_by_fkey FOREIGN KEY (conducted_by) REFERENCES auth.users(id)
);
CREATE TABLE public.expense_approvals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  approver_id uuid NOT NULL,
  level integer NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  remarks text,
  acted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT expense_approvals_pkey PRIMARY KEY (id),
  CONSTRAINT expense_approvals_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.expense_claims(id),
  CONSTRAINT expense_approvals_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT expense_approvals_approver_id_fkey FOREIGN KEY (approver_id) REFERENCES auth.users(id)
);
CREATE TABLE public.expense_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  code text NOT NULL,
  description text,
  requires_receipt boolean NOT NULL DEFAULT true,
  max_amount numeric,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT expense_categories_pkey PRIMARY KEY (id),
  CONSTRAINT expense_categories_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.expense_claims (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  category_id uuid,
  title text NOT NULL,
  description text,
  amount numeric NOT NULL,
  currency text NOT NULL DEFAULT 'PHP'::text,
  expense_date date NOT NULL,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'submitted'::text, 'under_review'::text, 'approved'::text, 'rejected'::text, 'reimbursed'::text, 'cancelled'::text])),
  submitted_at timestamp with time zone,
  approved_by uuid,
  approved_at timestamp with time zone,
  reimbursed_at timestamp with time zone,
  remarks text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT expense_claims_pkey PRIMARY KEY (id),
  CONSTRAINT expense_claims_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT expense_claims_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT expense_claims_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.expense_categories(id),
  CONSTRAINT expense_claims_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.hmo_dependents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_benefit_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  relationship text NOT NULL CHECK (relationship = ANY (ARRAY['spouse'::text, 'child'::text, 'parent'::text])),
  date_of_birth date,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hmo_dependents_pkey PRIMARY KEY (id),
  CONSTRAINT hmo_dependents_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT hmo_dependents_employee_benefit_id_fkey FOREIGN KEY (employee_benefit_id) REFERENCES public.employee_benefits(id),
  CONSTRAINT hmo_dependents_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.hmo_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  benefit_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  plan_name text NOT NULL,
  provider text NOT NULL,
  mbl numeric NOT NULL DEFAULT 0,
  room_board text,
  coverage_type text NOT NULL DEFAULT 'individual'::text CHECK (coverage_type = ANY (ARRAY['individual'::text, 'family'::text])),
  dependents_allowed integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hmo_plans_pkey PRIMARY KEY (id),
  CONSTRAINT hmo_plans_benefit_id_fkey FOREIGN KEY (benefit_id) REFERENCES public.benefits(id),
  CONSTRAINT hmo_plans_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.holidays (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  name text NOT NULL,
  date date NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['regular_holiday'::text, 'special_non_working'::text, 'special_working'::text, 'company'::text])),
  is_nationwide boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT holidays_pkey PRIMARY KEY (id),
  CONSTRAINT holidays_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.improvement_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  review_id uuid,
  title text NOT NULL,
  reason text NOT NULL,
  objectives text NOT NULL,
  support_provided text,
  start_date date NOT NULL,
  end_date date NOT NULL,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'completed'::text, 'extended'::text, 'terminated'::text])),
  outcome text CHECK (outcome = ANY (ARRAY['successful'::text, 'unsuccessful'::text, 'extended'::text])),
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT improvement_plans_pkey PRIMARY KEY (id),
  CONSTRAINT improvement_plans_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT improvement_plans_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT improvement_plans_review_id_fkey FOREIGN KEY (review_id) REFERENCES public.employee_reviews(id),
  CONSTRAINT improvement_plans_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.interview_interviewers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  interview_id uuid NOT NULL,
  interviewer_id uuid NOT NULL,
  rating integer CHECK (rating >= 1 AND rating <= 5),
  feedback text,
  submitted_at timestamp with time zone,
  CONSTRAINT interview_interviewers_pkey PRIMARY KEY (id),
  CONSTRAINT interview_interviewers_interview_id_fkey FOREIGN KEY (interview_id) REFERENCES public.interviews(id),
  CONSTRAINT interview_interviewers_interviewer_id_fkey FOREIGN KEY (interviewer_id) REFERENCES auth.users(id)
);
CREATE TABLE public.interviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  applicant_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  job_posting_id uuid NOT NULL,
  interview_type text NOT NULL DEFAULT 'initial'::text CHECK (interview_type = ANY (ARRAY['initial'::text, 'technical'::text, 'hr'::text, 'final'::text, 'panel'::text])),
  round integer NOT NULL DEFAULT 1,
  scheduled_at timestamp with time zone NOT NULL,
  duration_minutes integer NOT NULL DEFAULT 60,
  format text NOT NULL DEFAULT 'in_person'::text CHECK (format = ANY (ARRAY['in_person'::text, 'video'::text, 'phone'::text])),
  meeting_link text,
  location text,
  status text NOT NULL DEFAULT 'scheduled'::text CHECK (status = ANY (ARRAY['scheduled'::text, 'completed'::text, 'cancelled'::text, 'no_show'::text, 'rescheduled'::text])),
  overall_rating integer CHECK (overall_rating >= 1 AND overall_rating <= 5),
  recommendation text CHECK (recommendation = ANY (ARRAY['hire'::text, 'reject'::text, 'next_round'::text, 'hold'::text])),
  notes text,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT interviews_pkey PRIMARY KEY (id),
  CONSTRAINT interviews_applicant_id_fkey FOREIGN KEY (applicant_id) REFERENCES public.applicants(id),
  CONSTRAINT interviews_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT interviews_job_posting_id_fkey FOREIGN KEY (job_posting_id) REFERENCES public.job_postings(id),
  CONSTRAINT interviews_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.invite_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL,
  organization_id uuid NOT NULL,
  role_id uuid,
  token text NOT NULL DEFAULT encode(gen_random_bytes(32), 'hex'::text) UNIQUE,
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '7 days'::interval),
  accepted_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT invite_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT invite_tokens_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT invite_tokens_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id),
  CONSTRAINT invite_tokens_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.job_offers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  applicant_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  job_posting_id uuid NOT NULL,
  offered_salary numeric NOT NULL,
  start_date date NOT NULL,
  offer_letter_url text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'negotiating'::text, 'declined'::text, 'withdrawn'::text, 'expired'::text])),
  expires_at date,
  accepted_at timestamp with time zone,
  declined_at timestamp with time zone,
  decline_reason text,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT job_offers_pkey PRIMARY KEY (id),
  CONSTRAINT job_offers_applicant_id_fkey FOREIGN KEY (applicant_id) REFERENCES public.applicants(id),
  CONSTRAINT job_offers_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT job_offers_job_posting_id_fkey FOREIGN KEY (job_posting_id) REFERENCES public.job_postings(id),
  CONSTRAINT job_offers_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.job_postings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  department_id uuid,
  position_id uuid,
  title text NOT NULL,
  description text NOT NULL,
  requirements text,
  responsibilities text,
  employment_type text NOT NULL DEFAULT 'regular'::text CHECK (employment_type = ANY (ARRAY['regular'::text, 'probationary'::text, 'contractual'::text, 'project_based'::text, 'part_time'::text, 'internship'::text])),
  work_setup text NOT NULL DEFAULT 'on_site'::text CHECK (work_setup = ANY (ARRAY['on_site'::text, 'remote'::text, 'hybrid'::text])),
  location text,
  salary_min numeric,
  salary_max numeric,
  is_salary_visible boolean NOT NULL DEFAULT false,
  headcount integer NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'open'::text, 'on_hold'::text, 'closed'::text, 'cancelled'::text])),
  posted_at date,
  closes_at date,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT job_postings_pkey PRIMARY KEY (id),
  CONSTRAINT job_postings_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT job_postings_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT job_postings_position_id_fkey FOREIGN KEY (position_id) REFERENCES public.positions(id),
  CONSTRAINT job_postings_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.leave_approvals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  leave_request_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  approver_id uuid NOT NULL,
  level integer NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  remarks text,
  acted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT leave_approvals_pkey PRIMARY KEY (id),
  CONSTRAINT leave_approvals_leave_request_id_fkey FOREIGN KEY (leave_request_id) REFERENCES public.leave_requests(id),
  CONSTRAINT leave_approvals_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT leave_approvals_approver_id_fkey FOREIGN KEY (approver_id) REFERENCES auth.users(id)
);
CREATE TABLE public.leave_balances (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  leave_type_id uuid NOT NULL,
  year integer NOT NULL,
  entitled_days numeric NOT NULL DEFAULT 0,
  used_days numeric NOT NULL DEFAULT 0,
  pending_days numeric NOT NULL DEFAULT 0,
  carried_over numeric NOT NULL DEFAULT 0,
  balance numeric DEFAULT (((entitled_days + carried_over) - used_days) - pending_days),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT leave_balances_pkey PRIMARY KEY (id),
  CONSTRAINT leave_balances_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT leave_balances_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT leave_balances_leave_type_id_fkey FOREIGN KEY (leave_type_id) REFERENCES public.leave_types(id)
);
CREATE TABLE public.leave_credits_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  leave_type_id uuid NOT NULL,
  year integer NOT NULL,
  transaction_type text NOT NULL CHECK (transaction_type = ANY (ARRAY['accrual'::text, 'usage'::text, 'adjustment'::text, 'carry_over'::text, 'expiry'::text])),
  days numeric NOT NULL,
  reference_id uuid,
  notes text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT leave_credits_history_pkey PRIMARY KEY (id),
  CONSTRAINT leave_credits_history_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT leave_credits_history_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT leave_credits_history_leave_type_id_fkey FOREIGN KEY (leave_type_id) REFERENCES public.leave_types(id),
  CONSTRAINT leave_credits_history_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.leave_policies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  leave_type_id uuid NOT NULL,
  accrual_type text NOT NULL DEFAULT 'annual'::text CHECK (accrual_type = ANY (ARRAY['annual'::text, 'monthly'::text, 'per_pay_period'::text, 'manual'::text])),
  accrual_amount numeric NOT NULL DEFAULT 0,
  min_service_months integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT leave_policies_pkey PRIMARY KEY (id),
  CONSTRAINT leave_policies_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT leave_policies_leave_type_id_fkey FOREIGN KEY (leave_type_id) REFERENCES public.leave_types(id)
);
CREATE TABLE public.leave_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  leave_type_id uuid NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  total_days numeric NOT NULL,
  is_half_day boolean NOT NULL DEFAULT false,
  half_day_period text CHECK (half_day_period = ANY (ARRAY['am'::text, 'pm'::text])),
  reason text NOT NULL,
  document_url text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'cancelled'::text, 'withdrawn'::text])),
  approved_by uuid,
  approved_at timestamp with time zone,
  remarks text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT leave_requests_pkey PRIMARY KEY (id),
  CONSTRAINT leave_requests_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT leave_requests_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT leave_requests_leave_type_id_fkey FOREIGN KEY (leave_type_id) REFERENCES public.leave_types(id),
  CONSTRAINT leave_requests_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.leave_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  code text NOT NULL,
  description text,
  is_paid boolean NOT NULL DEFAULT true,
  is_mandatory boolean NOT NULL DEFAULT false,
  requires_document boolean NOT NULL DEFAULT false,
  max_days_per_year numeric,
  carry_over_days numeric NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT leave_types_pkey PRIMARY KEY (id),
  CONSTRAINT leave_types_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.loan_amortization (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  loan_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  period_number integer NOT NULL,
  due_date date NOT NULL,
  amount_due numeric NOT NULL,
  amount_paid numeric NOT NULL DEFAULT 0,
  balance_after numeric NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'paid'::text, 'partial'::text, 'missed'::text])),
  payslip_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT loan_amortization_pkey PRIMARY KEY (id),
  CONSTRAINT loan_amortization_loan_id_fkey FOREIGN KEY (loan_id) REFERENCES public.loans(id),
  CONSTRAINT loan_amortization_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT loan_amortization_payslip_id_fkey FOREIGN KEY (payslip_id) REFERENCES public.payslips(id)
);
CREATE TABLE public.loan_applications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  loan_type text NOT NULL CHECK (loan_type = ANY (ARRAY['sss_salary'::text, 'sss_calamity'::text, 'pagibig_mpl'::text, 'pagibig_calamity'::text, 'pagibig_housing'::text, 'company'::text, 'emergency'::text])),
  amount_requested numeric NOT NULL,
  term_months integer NOT NULL,
  purpose text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'under_review'::text, 'approved'::text, 'rejected'::text, 'disbursed'::text, 'cancelled'::text])),
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  approved_by uuid,
  approved_at timestamp with time zone,
  loan_id uuid,
  remarks text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT loan_applications_pkey PRIMARY KEY (id),
  CONSTRAINT loan_applications_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT loan_applications_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT loan_applications_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id),
  CONSTRAINT loan_applications_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id),
  CONSTRAINT loan_applications_loan_id_fkey FOREIGN KEY (loan_id) REFERENCES public.loans(id)
);
CREATE TABLE public.loans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  loan_type text NOT NULL CHECK (loan_type = ANY (ARRAY['sss_salary'::text, 'sss_calamity'::text, 'pagibig_mpl'::text, 'pagibig_calamity'::text, 'pagibig_housing'::text, 'company'::text, 'emergency'::text])),
  principal numeric NOT NULL,
  interest_rate numeric NOT NULL DEFAULT 0,
  term_months integer NOT NULL,
  monthly_amort numeric NOT NULL,
  outstanding_balance numeric NOT NULL,
  loan_date date NOT NULL,
  first_deduction_date date,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['pending'::text, 'active'::text, 'paid'::text, 'cancelled'::text, 'defaulted'::text])),
  approved_by uuid,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT loans_pkey PRIMARY KEY (id),
  CONSTRAINT loans_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT loans_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT loans_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.newsletter_subscribers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'active'::text, 'unsubscribed'::text])),
  unsubscribe_token text NOT NULL DEFAULT encode(gen_random_bytes(32), 'hex'::text) UNIQUE,
  subscribed_at timestamp with time zone,
  unsubscribed_at timestamp with time zone,
  ip_hash text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT newsletter_subscribers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notification_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  event_type text NOT NULL,
  in_app boolean NOT NULL DEFAULT true,
  email boolean NOT NULL DEFAULT true,
  sms boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notification_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT notification_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT notification_preferences_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.notification_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  event_type text NOT NULL,
  channel text NOT NULL CHECK (channel = ANY (ARRAY['in_app'::text, 'email'::text, 'sms'::text])),
  subject text,
  body text NOT NULL,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notification_templates_pkey PRIMARY KEY (id),
  CONSTRAINT notification_templates_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  recipient_id uuid NOT NULL,
  event_type text NOT NULL,
  title text NOT NULL,
  body text NOT NULL,
  action_url text,
  reference_type text,
  reference_id uuid,
  is_read boolean NOT NULL DEFAULT false,
  read_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT notifications_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES auth.users(id)
);
CREATE TABLE public.offboarding_checklists (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  is_default boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT offboarding_checklists_pkey PRIMARY KEY (id),
  CONSTRAINT offboarding_checklists_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.offboarding_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  checklist_id uuid,
  separation_type text NOT NULL CHECK (separation_type = ANY (ARRAY['resignation'::text, 'termination'::text, 'retirement'::text, 'end_of_contract'::text, 'redundancy'::text, 'death'::text])),
  last_day_of_work date NOT NULL,
  clearance_status text NOT NULL DEFAULT 'pending'::text CHECK (clearance_status = ANY (ARRAY['pending'::text, 'in_progress'::text, 'cleared'::text, 'held'::text])),
  final_pay_status text NOT NULL DEFAULT 'pending'::text CHECK (final_pay_status = ANY (ARRAY['pending'::text, 'computed'::text, 'approved'::text, 'released'::text])),
  final_pay_amount numeric,
  final_pay_date date,
  notes text,
  initiated_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT offboarding_records_pkey PRIMARY KEY (id),
  CONSTRAINT offboarding_records_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT offboarding_records_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT offboarding_records_checklist_id_fkey FOREIGN KEY (checklist_id) REFERENCES public.offboarding_checklists(id),
  CONSTRAINT offboarding_records_initiated_by_fkey FOREIGN KEY (initiated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.onboarding_progress (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  workflow_id uuid NOT NULL,
  task_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'in_progress'::text, 'completed'::text, 'skipped'::text])),
  due_date date,
  completed_at timestamp with time zone,
  completed_by uuid,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT onboarding_progress_pkey PRIMARY KEY (id),
  CONSTRAINT onboarding_progress_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT onboarding_progress_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT onboarding_progress_workflow_id_fkey FOREIGN KEY (workflow_id) REFERENCES public.onboarding_workflows(id),
  CONSTRAINT onboarding_progress_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.onboarding_tasks(id),
  CONSTRAINT onboarding_progress_completed_by_fkey FOREIGN KEY (completed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.onboarding_tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  workflow_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  category text NOT NULL DEFAULT 'general'::text CHECK (category = ANY (ARRAY['documents'::text, 'it_setup'::text, 'orientation'::text, 'training'::text, 'compliance'::text, 'general'::text])),
  assigned_to_role text,
  due_days_after_hire integer NOT NULL DEFAULT 1,
  is_required boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT onboarding_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT onboarding_tasks_workflow_id_fkey FOREIGN KEY (workflow_id) REFERENCES public.onboarding_workflows(id),
  CONSTRAINT onboarding_tasks_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.onboarding_workflows (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  department_id uuid,
  position_id uuid,
  is_default boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT onboarding_workflows_pkey PRIMARY KEY (id),
  CONSTRAINT onboarding_workflows_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT onboarding_workflows_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT onboarding_workflows_position_id_fkey FOREIGN KEY (position_id) REFERENCES public.positions(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  plan text NOT NULL DEFAULT 'trial'::text CHECK (plan = ANY (ARRAY['trial'::text, 'starter'::text, 'pro'::text, 'enterprise'::text])),
  industry text,
  company_size text,
  trial_ends_at timestamp with time zone NOT NULL DEFAULT (now() + '14 days'::interval),
  is_active boolean NOT NULL DEFAULT true,
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  logo_url text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.overtime_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  request_date date NOT NULL,
  ot_start timestamp with time zone NOT NULL,
  ot_end timestamp with time zone NOT NULL,
  ot_hours numeric,
  ot_type text NOT NULL DEFAULT 'regular'::text CHECK (ot_type = ANY (ARRAY['regular'::text, 'rest_day'::text, 'regular_holiday'::text, 'special_non_working'::text, 'night_differential'::text])),
  reason text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'cancelled'::text])),
  approved_by uuid,
  approved_at timestamp with time zone,
  remarks text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT overtime_requests_pkey PRIMARY KEY (id),
  CONSTRAINT overtime_requests_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT overtime_requests_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT overtime_requests_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.pagibig_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  pagibig_no text,
  period_year integer NOT NULL,
  period_month integer NOT NULL CHECK (period_month >= 1 AND period_month <= 12),
  monthly_compensation numeric NOT NULL DEFAULT 0,
  ee_contribution numeric NOT NULL DEFAULT 0,
  er_contribution numeric NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pagibig_records_pkey PRIMARY KEY (id),
  CONSTRAINT pagibig_records_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.compliance_reports(id),
  CONSTRAINT pagibig_records_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT pagibig_records_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.payroll_disputes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  payslip_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  reason text NOT NULL,
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'under_review'::text, 'resolved'::text, 'rejected'::text])),
  resolution text,
  resolved_by uuid,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payroll_disputes_pkey PRIMARY KEY (id),
  CONSTRAINT payroll_disputes_payslip_id_fkey FOREIGN KEY (payslip_id) REFERENCES public.payslips(id),
  CONSTRAINT payroll_disputes_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT payroll_disputes_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT payroll_disputes_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.payroll_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  payslip_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['earning'::text, 'deduction'::text])),
  category text NOT NULL,
  description text NOT NULL,
  amount numeric NOT NULL DEFAULT 0,
  is_taxable boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payroll_items_pkey PRIMARY KEY (id),
  CONSTRAINT payroll_items_payslip_id_fkey FOREIGN KEY (payslip_id) REFERENCES public.payslips(id),
  CONSTRAINT payroll_items_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.payroll_periods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  frequency text NOT NULL DEFAULT 'semi_monthly'::text CHECK (frequency = ANY (ARRAY['weekly'::text, 'bi_weekly'::text, 'semi_monthly'::text, 'monthly'::text])),
  period_start date NOT NULL,
  period_end date NOT NULL,
  pay_date date NOT NULL,
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'processing'::text, 'for_approval'::text, 'approved'::text, 'released'::text, 'closed'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payroll_periods_pkey PRIMARY KEY (id),
  CONSTRAINT payroll_periods_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.payroll_runs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  payroll_period_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'computed'::text, 'reviewed'::text, 'approved'::text, 'released'::text])),
  total_employees integer NOT NULL DEFAULT 0,
  total_gross_pay numeric NOT NULL DEFAULT 0,
  total_deductions numeric NOT NULL DEFAULT 0,
  total_net_pay numeric NOT NULL DEFAULT 0,
  computed_at timestamp with time zone,
  computed_by uuid,
  approved_at timestamp with time zone,
  approved_by uuid,
  released_at timestamp with time zone,
  released_by uuid,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payroll_runs_pkey PRIMARY KEY (id),
  CONSTRAINT payroll_runs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT payroll_runs_payroll_period_id_fkey FOREIGN KEY (payroll_period_id) REFERENCES public.payroll_periods(id),
  CONSTRAINT payroll_runs_computed_by_fkey FOREIGN KEY (computed_by) REFERENCES auth.users(id),
  CONSTRAINT payroll_runs_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id),
  CONSTRAINT payroll_runs_released_by_fkey FOREIGN KEY (released_by) REFERENCES auth.users(id)
);
CREATE TABLE public.payslips (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  payroll_run_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  payroll_period_id uuid NOT NULL,
  basic_pay numeric NOT NULL DEFAULT 0,
  overtime_pay numeric NOT NULL DEFAULT 0,
  holiday_pay numeric NOT NULL DEFAULT 0,
  night_diff_pay numeric NOT NULL DEFAULT 0,
  allowances numeric NOT NULL DEFAULT 0,
  other_earnings numeric NOT NULL DEFAULT 0,
  gross_pay numeric NOT NULL DEFAULT 0,
  sss_ee numeric NOT NULL DEFAULT 0,
  philhealth_ee numeric NOT NULL DEFAULT 0,
  pagibig_ee numeric NOT NULL DEFAULT 0,
  withholding_tax numeric NOT NULL DEFAULT 0,
  sss_er numeric NOT NULL DEFAULT 0,
  philhealth_er numeric NOT NULL DEFAULT 0,
  pagibig_er numeric NOT NULL DEFAULT 0,
  loan_deductions numeric NOT NULL DEFAULT 0,
  late_deductions numeric NOT NULL DEFAULT 0,
  absent_deductions numeric NOT NULL DEFAULT 0,
  other_deductions numeric NOT NULL DEFAULT 0,
  total_deductions numeric NOT NULL DEFAULT 0,
  net_pay numeric NOT NULL DEFAULT 0,
  days_worked numeric NOT NULL DEFAULT 0,
  hours_worked numeric NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'approved'::text, 'released'::text, 'disputed'::text])),
  pdf_url text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payslips_pkey PRIMARY KEY (id),
  CONSTRAINT payslips_payroll_run_id_fkey FOREIGN KEY (payroll_run_id) REFERENCES public.payroll_runs(id),
  CONSTRAINT payslips_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT payslips_payroll_period_id_fkey FOREIGN KEY (payroll_period_id) REFERENCES public.payroll_periods(id),
  CONSTRAINT payslips_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  module text NOT NULL,
  action text NOT NULL,
  description text,
  CONSTRAINT permissions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.philhealth_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  philhealth_no text,
  period_year integer NOT NULL,
  period_month integer NOT NULL CHECK (period_month >= 1 AND period_month <= 12),
  basic_salary numeric NOT NULL DEFAULT 0,
  ee_contribution numeric NOT NULL DEFAULT 0,
  er_contribution numeric NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT philhealth_records_pkey PRIMARY KEY (id),
  CONSTRAINT philhealth_records_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT philhealth_records_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT philhealth_records_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.compliance_reports(id)
);
CREATE TABLE public.positions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  department_id uuid,
  title text NOT NULL,
  code text,
  level text CHECK (level = ANY (ARRAY['entry'::text, 'junior'::text, 'mid'::text, 'senior'::text, 'lead'::text, 'manager'::text, 'director'::text, 'executive'::text])),
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT positions_pkey PRIMARY KEY (id),
  CONSTRAINT positions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT positions_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.rate_limits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ip_hash text NOT NULL,
  action text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT rate_limits_pkey PRIMARY KEY (id)
);
CREATE TABLE public.receipts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  file_name text NOT NULL,
  file_url text NOT NULL,
  file_size integer,
  mime_type text,
  uploaded_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT receipts_pkey PRIMARY KEY (id),
  CONSTRAINT receipts_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.expense_claims(id),
  CONSTRAINT receipts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.reimbursements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  amount numeric NOT NULL,
  payment_method text NOT NULL DEFAULT 'bank_transfer'::text CHECK (payment_method = ANY (ARRAY['bank_transfer'::text, 'cash'::text, 'payroll_inclusion'::text])),
  reference_no text,
  paid_at timestamp with time zone,
  payslip_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT reimbursements_pkey PRIMARY KEY (id),
  CONSTRAINT reimbursements_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.expense_claims(id),
  CONSTRAINT reimbursements_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT reimbursements_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT reimbursements_payslip_id_fkey FOREIGN KEY (payslip_id) REFERENCES public.payslips(id)
);
CREATE TABLE public.review_criteria (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  category text NOT NULL CHECK (category = ANY (ARRAY['kpi'::text, 'competency'::text, 'values'::text, 'goals'::text])),
  name text NOT NULL,
  description text,
  weight numeric NOT NULL DEFAULT 0,
  max_score integer NOT NULL DEFAULT 5,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT review_criteria_pkey PRIMARY KEY (id),
  CONSTRAINT review_criteria_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.review_templates(id),
  CONSTRAINT review_criteria_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.review_cycles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['annual'::text, 'semi_annual'::text, 'quarterly'::text, 'probationary'::text, 'ad_hoc'::text])),
  period_start date NOT NULL,
  period_end date NOT NULL,
  review_due_date date NOT NULL,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'completed'::text, 'cancelled'::text])),
  instructions text,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT review_cycles_pkey PRIMARY KEY (id),
  CONSTRAINT review_cycles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT review_cycles_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.review_scores (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  review_id uuid NOT NULL,
  criteria_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  self_score numeric,
  manager_score numeric,
  self_comments text,
  manager_comments text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT review_scores_pkey PRIMARY KEY (id),
  CONSTRAINT review_scores_review_id_fkey FOREIGN KEY (review_id) REFERENCES public.employee_reviews(id),
  CONSTRAINT review_scores_criteria_id_fkey FOREIGN KEY (criteria_id) REFERENCES public.review_criteria(id),
  CONSTRAINT review_scores_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.review_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  is_default boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT review_templates_pkey PRIMARY KEY (id),
  CONSTRAINT review_templates_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.role_permissions (
  role_id uuid NOT NULL,
  permission_id uuid NOT NULL,
  CONSTRAINT role_permissions_pkey PRIMARY KEY (role_id, permission_id),
  CONSTRAINT role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id),
  CONSTRAINT role_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.permissions(id)
);
CREATE TABLE public.roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  name text NOT NULL,
  slug text NOT NULL,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT roles_pkey PRIMARY KEY (id),
  CONSTRAINT roles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.salary_adjustments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  payroll_run_id uuid,
  type text NOT NULL CHECK (type = ANY (ARRAY['bonus'::text, 'allowance'::text, 'deduction'::text, 'reimbursement'::text, 'adjustment'::text])),
  description text NOT NULL,
  amount numeric NOT NULL,
  is_taxable boolean NOT NULL DEFAULT true,
  effective_date date NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'applied'::text, 'cancelled'::text])),
  approved_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT salary_adjustments_pkey PRIMARY KEY (id),
  CONSTRAINT salary_adjustments_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT salary_adjustments_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT salary_adjustments_payroll_run_id_fkey FOREIGN KEY (payroll_run_id) REFERENCES public.payroll_runs(id),
  CONSTRAINT salary_adjustments_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.saved_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  report_type text NOT NULL CHECK (report_type = ANY (ARRAY['headcount'::text, 'turnover'::text, 'attendance'::text, 'leave'::text, 'payroll'::text, 'benefits'::text, 'performance'::text, 'recruitment'::text, 'custom'::text])),
  filters jsonb NOT NULL DEFAULT '{}'::jsonb,
  columns ARRAY NOT NULL DEFAULT '{}'::text[],
  sort_by text,
  is_scheduled boolean NOT NULL DEFAULT false,
  schedule_cron text,
  last_run_at timestamp with time zone,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT saved_reports_pkey PRIMARY KEY (id),
  CONSTRAINT saved_reports_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT saved_reports_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.schedules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  code text NOT NULL,
  shift_start time without time zone NOT NULL,
  shift_end time without time zone NOT NULL,
  break_minutes integer NOT NULL DEFAULT 60,
  work_hours numeric NOT NULL DEFAULT 8,
  is_night_shift boolean NOT NULL DEFAULT false,
  is_flexible boolean NOT NULL DEFAULT false,
  grace_period_minutes integer NOT NULL DEFAULT 15,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT schedules_pkey PRIMARY KEY (id),
  CONSTRAINT schedules_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.security_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  user_id uuid,
  email text,
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['login_success'::text, 'login_failed'::text, 'logout'::text, 'password_reset_requested'::text, 'password_reset_completed'::text, 'mfa_enabled'::text, 'mfa_disabled'::text, 'mfa_challenge_failed'::text, 'session_expired'::text, 'account_locked'::text, 'account_unlocked'::text, 'invite_sent'::text, 'invite_accepted'::text])),
  ip_address text,
  user_agent text,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT security_events_pkey PRIMARY KEY (id),
  CONSTRAINT security_events_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT security_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.sss_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  sss_no text,
  period_year integer NOT NULL,
  period_month integer NOT NULL CHECK (period_month >= 1 AND period_month <= 12),
  monthly_salary_credit numeric NOT NULL DEFAULT 0,
  ee_contribution numeric NOT NULL DEFAULT 0,
  er_contribution numeric NOT NULL DEFAULT 0,
  ec_contribution numeric NOT NULL DEFAULT 0,
  total_contribution numeric NOT NULL DEFAULT 0,
  is_mpe boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sss_records_pkey PRIMARY KEY (id),
  CONSTRAINT sss_records_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.compliance_reports(id),
  CONSTRAINT sss_records_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT sss_records_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.thirteenth_month_pay (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  year integer NOT NULL,
  total_basic_pay numeric NOT NULL DEFAULT 0,
  months_worked numeric NOT NULL DEFAULT 12,
  amount numeric NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'released'::text])),
  payslip_id uuid,
  released_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT thirteenth_month_pay_pkey PRIMARY KEY (id),
  CONSTRAINT thirteenth_month_pay_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT thirteenth_month_pay_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT thirteenth_month_pay_payslip_id_fkey FOREIGN KEY (payslip_id) REFERENCES public.payslips(id)
);
CREATE TABLE public.turnover_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  department_id uuid,
  position_id uuid,
  separation_type text NOT NULL CHECK (separation_type = ANY (ARRAY['resignation'::text, 'termination'::text, 'retirement'::text, 'redundancy'::text, 'end_of_contract'::text, 'death'::text, 'abandonment'::text])),
  separation_date date NOT NULL,
  tenure_months integer,
  last_salary numeric,
  exit_interview_done boolean NOT NULL DEFAULT false,
  rehire_eligible boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT turnover_records_pkey PRIMARY KEY (id),
  CONSTRAINT turnover_records_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT turnover_records_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT turnover_records_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT turnover_records_position_id_fkey FOREIGN KEY (position_id) REFERENCES public.positions(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL,
  organization_id uuid,
  employee_id text,
  full_name text NOT NULL DEFAULT ''::text,
  avatar_url text,
  phone text,
  is_active boolean NOT NULL DEFAULT true,
  must_change_password boolean NOT NULL DEFAULT false,
  last_login_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT user_profiles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.user_roles (
  user_id uuid NOT NULL,
  role_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id, organization_id),
  CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_roles_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id),
  CONSTRAINT user_roles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.workforce_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  department_id uuid,
  plan_year integer NOT NULL,
  current_headcount integer NOT NULL DEFAULT 0,
  target_headcount integer NOT NULL DEFAULT 0,
  planned_hires integer NOT NULL DEFAULT 0,
  planned_exits integer NOT NULL DEFAULT 0,
  budget_allocation numeric,
  notes text,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'approved'::text, 'active'::text, 'closed'::text])),
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT workforce_plans_pkey PRIMARY KEY (id),
  CONSTRAINT workforce_plans_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT workforce_plans_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT workforce_plans_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);